name: Deploy Java Website

on:
  push:
    branches:
      - main  # Runs when code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project with Maven
        run: mvn clean package

      - name: Add remote server to known hosts
        run: |
          mkdir -p ~/.ssh
          # Use ssh-keyscan to add EC2 host to known_hosts
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
          # Make sure the permissions of the file are correct
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy to AWS EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: "43.204.85.137"
          USER: "ubuntu"
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -i private_key $USER@$SERVER_IP "echo 'SSH connection successful!'"
          scp -i private_key target/bookstore.jar $USER@$SERVER_IP:/home/ubuntu/java-project/target/bookstore.jar
          ssh -i private_key $USER@$SERVER_IP << 'EOF'
            nohup java -jar /home/ubuntu/java-project/target/bookstore.jar > /home/ubuntu/logs.txt 2>&1 &
          EOF
         
