name: Deploy Java Website

on:
  push:
    branches:
      - main  # Runs when code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project with Maven
        run: mvn clean package

      - name: Deploy to AWS EC2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: "43.204.85.137"
          USER: "ubuntu"
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          scp -i private_key bookstore.jar $USER@$43.204.85.137:/home/ubuntu/java-project/target/bookstore.jar
          ssh -i private_key $USER@$43.204.85.137 << 'EOF'
            nohup java -jar /home/ubuntu/java-project/target/bookstore.jar > /home/ubuntu/logs.txt 2>&1 &
          EOF
